### ISSUE TITLE
Not working on playlists anymore

### ISSUE THREAD

**Issue by Zegjita** [snoringriceball/youtube-sleep-timer#11]
I'll usually leave a playlist up and running, and set it to 60/90 minutes, and it has worked great until maybe the last week or two? It turns off when swapping to the next video on a playlist.

**Comment by snoringriceball** [comment]
Hello~ thanks for reporting the issue.
Would you kindly supply the version of chrome you are using?
We're a bit short staffed right now, so would be fantastic if we can get some open source contributors :) but we'll get around to fixing it as soon as we find time.
Thanks for your continuous support.

**Comment by Zegjita** [comment]
Version 102.0.5005.63 (64-bit)

**Comment by snoringriceball** [comment]
Version 102.0.5005.115 (Official Build) (x86_64)
Hello! I tested a few times over the past few weeks, and re-tested again today after the latest update to the build version referenced above.
I set the timer to one minute, and switched between different videos in a playlist by clicking the "next" button on youtube. I also switched videos by clicking directly on recommended videos. The extension still paused the current playing video after the timer went off, although sometimes with a few seconds delay.
May I ask if the extension is still not working for you? If you load the extension unpacked, does the same issue occur?

**Comment by Zegjita** [comment]
Hello again. After I posted this I tried it a few more times, without it working correctly just to make sure, then I didn't touch it until you sent this message. I tested it just now and it appears to be working again? I'm unsure why though. My version doesn't appear to be different. I apologize for any inconvenience I caused you.

**Comment by snoringriceball** [comment]
Marking this as closed since the current version has been stable for four months :)
